export const carFiles = [
    { obj: "/models/car-coupe-blue.obj", mtl: "/models/car-coupe-blue.mtl" },
    { obj: "/models/car-coupe-citrus.obj", mtl: "/models/car-coupe-citrus.mtl" },
    { obj: "/models/car-coupe-green.obj", mtl: "/models/car-coupe-green.mtl" },
    { obj: "/models/car-coupe-orange.obj", mtl: "/models/car-coupe-orange.mtl" },
    { obj: "/models/car-coupe-red.obj", mtl: "/models/car-coupe-red.mtl" },
    { obj: "/models/car-coupe-silver.obj", mtl: "/models/car-coupe-silver.mtl" },
    { obj: "/models/car-coupe-violet.obj", mtl: "/models/car-coupe-violet.mtl" },

    { obj: "/models/car-hatchback-blue.obj", mtl: "/models/car-hatchback-blue.mtl" },
    { obj: "/models/car-hatchback-citrus.obj", mtl: "/models/car-hatchback-citrus.mtl" },
    { obj: "/models/car-hatchback-green.obj", mtl: "/models/car-hatchback-green.mtl" },
    { obj: "/models/car-hatchback-orange.obj", mtl: "/models/car-hatchback-orange.mtl" },
    { obj: "/models/car-hatchback-red.obj", mtl: "/models/car-hatchback-red.mtl" },
    { obj: "/models/car-hatchback-silver.obj", mtl: "/models/car-hatchback-silver.mtl" },
    { obj: "/models/car-hatchback-violet.obj", mtl: "/models/car-hatchback-violet.mtl" },

    { obj: "/models/car-micro-blue.obj", mtl: "/models/car-micro-blue.mtl" },
    { obj: "/models/car-micro-citrus.obj", mtl: "/models/car-micro-citrus.mtl" },
    { obj: "/models/car-micro-green.obj", mtl: "/models/car-micro-green.mtl" },
    { obj: "/models/car-micro-orange.obj", mtl: "/models/car-micro-orange.mtl" },
    { obj: "/models/car-micro-red.obj", mtl: "/models/car-micro-red.mtl" },
    { obj: "/models/car-micro-silver.obj", mtl: "/models/car-micro-silver.mtl" },
    { obj: "/models/car-micro-violet.obj", mtl: "/models/car-micro-violet.mtl" },

    { obj: "/models/car-microcargo-blue.obj", mtl: "/models/car-microcargo-blue.mtl" },
    { obj: "/models/car-microcargo-citrus.obj", mtl: "/models/car-microcargo-citrus.mtl" },
    { obj: "/models/car-microcargo-green.obj", mtl: "/models/car-microcargo-green.mtl" },
    { obj: "/models/car-microcargo-orange.obj", mtl: "/models/car-microcargo-orange.mtl" },
    { obj: "/models/car-microcargo-red.obj", mtl: "/models/car-microcargo-red.mtl" },
    { obj: "/models/car-microcargo-silver.obj", mtl: "/models/car-microcargo-silver.mtl" },
    { obj: "/models/car-microcargo-violet.obj", mtl: "/models/car-microcargo-violet.mtl" },

    { obj: "/models/car-microtransport-blue.obj", mtl: "/models/car-microtransport-blue.mtl" },
    { obj: "/models/car-microtransport-citrus.obj", mtl: "/models/car-microtransport-citrus.mtl" },
    { obj: "/models/car-microtransport-green.obj", mtl: "/models/car-microtransport-green.mtl" },
    { obj: "/models/car-microtransport-orange.obj", mtl: "/models/car-microtransport-orange.mtl" },
    { obj: "/models/car-microtransport-red.obj", mtl: "/models/car-microtransport-red.mtl" },
    { obj: "/models/car-microtransport-silver.obj", mtl: "/models/car-microtransport-silver.mtl" },
    { obj: "/models/car-microtransport-violet.obj", mtl: "/models/car-microtransport-violet.mtl" },

    { obj: "/models/car-minibus-blue.obj", mtl: "/models/car-minibus-blue.mtl" },
    { obj: "/models/car-minibus-citrus.obj", mtl: "/models/car-minibus-citrus.mtl" },
    { obj: "/models/car-minibus-green.obj", mtl: "/models/car-minibus-green.mtl" },
    { obj: "/models/car-minibus-orange.obj", mtl: "/models/car-minibus-orange.mtl" },
    { obj: "/models/car-minibus-red.obj", mtl: "/models/car-minibus-red.mtl" },
    { obj: "/models/car-minibus-silver.obj", mtl: "/models/car-minibus-silver.mtl" },
    { obj: "/models/car-minibus-violet.obj", mtl: "/models/car-minibus-violet.mtl" },

    { obj: "/models/car-mpv-blue.obj", mtl: "/models/car-mpv-blue.mtl" },
    { obj: "/models/car-mpv-citrus.obj", mtl: "/models/car-mpv-citrus.mtl" },
    { obj: "/models/car-mpv-green.obj", mtl: "/models/car-mpv-green.mtl" },
    { obj: "/models/car-mpv-orange.obj", mtl: "/models/car-mpv-orange.mtl" },
    { obj: "/models/car-mpv-red.obj", mtl: "/models/car-mpv-red.mtl" },
    { obj: "/models/car-mpv-silver.obj", mtl: "/models/car-mpv-silver.mtl" },
    { obj: "/models/car-mpv-violet.obj", mtl: "/models/car-mpv-violet.mtl" },

    { obj: "/models/car-normal-blue.obj", mtl: "/models/car-normal-blue.mtl" },
    { obj: "/models/car-normal-citrus.obj", mtl: "/models/car-normal-citrus.mtl" },
    { obj: "/models/car-normal-green.obj", mtl: "/models/car-normal-green.mtl" },
    { obj: "/models/car-normal-orange.obj", mtl: "/models/car-normal-orange.mtl" },
    { obj: "/models/car-normal-red.obj", mtl: "/models/car-normal-red.mtl" },
    { obj: "/models/car-normal-silver.obj", mtl: "/models/car-normal-silver.mtl" },
    { obj: "/models/car-normal-violet.obj", mtl: "/models/car-normal-violet.mtl" },

    { obj: "/models/car-pickup-blue.obj", mtl: "/models/car-pickup-blue.mtl" },
    { obj: "/models/car-pickup-citrus.obj", mtl: "/models/car-pickup-citrus.mtl" },
    { obj: "/models/car-pickup-green.obj", mtl: "/models/car-pickup-green.mtl" },
    { obj: "/models/car-pickup-orange.obj", mtl: "/models/car-pickup-orange.mtl" },
    { obj: "/models/car-pickup-red.obj", mtl: "/models/car-pickup-red.mtl" },
    { obj: "/models/car-pickup-silver.obj", mtl: "/models/car-pickup-silver.mtl" },
    { obj: "/models/car-pickup-violet.obj", mtl: "/models/car-pickup-violet.mtl" },

    { obj: "/models/car-pickup-small-blue.obj", mtl: "/models/car-pickup-small-blue.mtl" },
    { obj: "/models/car-pickup-small-citrus.obj", mtl: "/models/car-pickup-small-citrus.mtl" },
    { obj: "/models/car-pickup-small-green.obj", mtl: "/models/car-pickup-small-green.mtl" },
    { obj: "/models/car-pickup-small-orange.obj", mtl: "/models/car-pickup-small-orange.mtl" },
    { obj: "/models/car-pickup-small-red.obj", mtl: "/models/car-pickup-small-red.mtl" },
    { obj: "/models/car-pickup-small-silver.obj", mtl: "/models/car-pickup-small-silver.mtl" },
    { obj: "/models/car-pickup-small-violet.obj", mtl: "/models/car-pickup-small-violet.mtl" },

    { obj: "/models/car-station-blue.obj", mtl: "/models/car-station-blue.mtl" },
    { obj: "/models/car-station-citrus.obj", mtl: "/models/car-station-citrus.mtl" },
    { obj: "/models/car-station-green.obj", mtl: "/models/car-station-green.mtl" },
    { obj: "/models/car-station-orange.obj", mtl: "/models/car-station-orange.mtl" },
    { obj: "/models/car-station-red.obj", mtl: "/models/car-station-red.mtl" },
    { obj: "/models/car-station-silver.obj", mtl: "/models/car-station-silver.mtl" },
    { obj: "/models/car-station-violet.obj", mtl: "/models/car-station-violet.mtl" },

    { obj: "/models/car-van-blue.obj", mtl: "/models/car-van-blue.mtl" },
    { obj: "/models/car-van-citrus.obj", mtl: "/models/car-van-citrus.mtl" },
    { obj: "/models/car-van-green.obj", mtl: "/models/car-van-green.mtl" },
    { obj: "/models/car-van-orange.obj", mtl: "/models/car-van-orange.mtl" },
];
